# Generated by Django 4.2.1 on 2023-06-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('ALL', 'Все'), ('M', 'Мужской'), ('K', 'Детский'), ('W', 'Женский')], default='ALL', max_length=3),
        ),
    ]
