# Generated by Django 4.2.2 on 2023-06-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('W', 'Женский'), ('K', 'Детский'), ('ALL', 'Все'), ('M', 'Мужской')], default='ALL', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test-object', max_length=200),
        ),
    ]
