# Generated by Django 4.2.2 on 2023-06-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_gender_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('K', 'Детский'), ('M', 'Мужской'), ('ALL', 'Все'), ('W', 'Женский')], default='ALL', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test-object', max_length=200, null=True),
        ),
    ]
